import Head from 'next/head'
import { getConfig } from "@bigcommerce/storefront-data-hooks/api";
import getProduct from "@bigcommerce/storefront-data-hooks/api/operations/get-product";
import getAllProducts from "@bigcommerce/storefront-data-hooks/api/operations/get-all-products";
import LandingPage from '../components/home/landingPage';

export async function getStaticProps() {
  // Fetch data from external API
  const config = getConfig({ locale: "en-US" });
  const { products } = await getAllProducts({
    config,
    preview: true,
  });
  const { product } = await getProduct({
    variables: { path: "/tiered-wire-basket/" },
    config,
    preview: true,
  });
  console.log(product);

  return { props: { products } };
}

export default function Home(props) {

  return (
    <div>
      <Head>
        <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin></script>

        <script
          src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
          crossorigin></script>

        <script
          src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossorigin></script>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPage data={props.products} />
    </div>
  );
}